software:
    path:     /
    defaults: { _controller: "uniSistemasBundle:software:index" }

software_show:
    path:     /{id}/show
    defaults: { _controller: "uniSistemasBundle:software:show" }

software_new:
    path:     /new
    defaults: { _controller: "uniSistemasBundle:software:new" }

software_create:
    path:     /create
    defaults: { _controller: "uniSistemasBundle:software:create" }
    requirements: { _method: post }

software_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniSistemasBundle:software:edit" }

software_update:
    path:     /{id}/update
    defaults: { _controller: "uniSistemasBundle:software:update" }
    requirements: { _method: post|put }

software_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniSistemasBundle:software:delete" }
    requirements: { _method: post|delete }
    
buscSW:
    path:     /buscSW
    defaults: { _controller: "uniSistemasBundle:software:buscarSW" }
    
respBuscSW:
    path:     /respBuscSW
    defaults: { _controller: "uniSistemasBundle:software:respBuscSW" }
